default:
  image: amazoncorretto:11.0.7
  before_script:
    - ': before_script'
    - chmod +x gradlew
    - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - build

build:
  stage: build
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

test:
  stage: test
  script:
    - ': script'
    - ./gradlew check -i
